INSERT INTO CATEGORIAS (ID, Nome)
VALUES
    (NEWID(), 'BEBIDAS'),
    (NEWID(), 'HORTIFRUTI'),
    (NEWID(), 'PADARIA'),
    (NEWID(), 'LATICÍNIOS'),
    (NEWID(), 'CARNES'),
    (NEWID(), 'LIMPEZA');

SELECT * FROM CATEGORIAS
ORDER BY Nome ASC;
